DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT,
    FIRST_NAME VARCHAR(255),
    SECOND_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PRIMARY KEY (ID));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT,
    GENRE_NAME VARCHAR(255),
    primary key (ID));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT,
    BOOK_NAME VARCHAR(255),
    PUBLISH_DATE DATE,
    AUTHOR_ID NUMBER REFERENCES AUTHOR,
    GENRE_ID NUMBER REFERENCES GENRE, PRIMARY KEY (ID)) ;
