DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRIMARY KEY (ID));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    primary key (ID));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    AUTHOR_ID NUMBER REFERENCES AUTHOR,
    GENRE_ID NUMBER REFERENCES GENRE, PRIMARY KEY (ID)) ;
